# Testing 

In [1]:
import numpy as np
from cvxopt import matrix, solvers

In [2]:
# define random Q
Q = np.array([[1,1,1,1],[2,2,2,2], [3,3,3,3], [4,4,4,4]])
Q

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

## Checking Friend's Code

In [3]:
row_A = np.array(-Q, dtype="float") # -1 to minimize
row_b = np.zeros(len(row_A), dtype="float")

In [4]:
row_A

array([[-1., -1., -1., -1.],
       [-2., -2., -2., -2.],
       [-3., -3., -3., -3.],
       [-4., -4., -4., -4.]])

In [5]:
row_b

array([0., 0., 0., 0.])

In [6]:
# define 4 actions (they had 5 actions)
actions = 4

# (5) Probability constraint
prob_A = -np.identity(actions, dtype="float")
prob_b = np.zeros(actions, dtype="float")

In [7]:
prob_A

array([[-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.]])

In [8]:
prob_b

array([0., 0., 0., 0.])

In [9]:
# (2) Equality constraints Sum(prob) = 1
equality_A = np.array([np.ones((actions)), -np.ones((actions))], dtype="float")
equality_b = np.array([1, -1], dtype="float")

In [10]:
equality_A

array([[ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.]])

In [11]:
equality_b

array([ 1., -1.])

In [12]:
#  Auxiliary variable Z
z = np.array([1.0 for i in range(actions)] + [0.0 for i in range(actions + 2)])
A = matrix(np.hstack((np.vstack((np.transpose(row_A), prob_A, equality_A)), z.reshape(z.size, 1))))
b = matrix(np.concatenate((row_b, prob_b, equality_b)))
c = matrix(np.hstack(([0.0 for i in range(actions)], [-1.0])))

In [13]:
z

array([1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [14]:
A

<10x5 matrix, tc='d'>

In [15]:
b

<10x1 matrix, tc='d'>

In [16]:
c

<5x1 matrix, tc='d'>

In [17]:
solvers.options['glpk'] = {'msg_lev' : 'GLP_MSG_OFF'}
solution = solvers.lp(c, A, b, solver='glpk')

In [18]:
solution

{'dual infeasibility': 0.0,
 'dual objective': -4.0,
 'dual slack': -0.0,
 'gap': 0.0,
 'primal infeasibility': 0.0,
 'primal objective': -4.0,
 'primal slack': 0.0,
 'relative gap': 0.0,
 'residual as dual infeasibility certificate': None,
 'residual as primal infeasibility certificate': None,
 's': <10x1 matrix, tc='d'>,
 'status': 'optimal',
 'x': <5x1 matrix, tc='d'>,
 'y': <0x1 matrix, tc='d'>,
 'z': <10x1 matrix, tc='d'>}